import {
  Geist,
  Azeret_Mono as Geist_Mono,
  Poppins,
  Montserrat,
} from "next/font/google";
import { ThemeProvider } from "@/components/ThemeProvider";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Jioh In",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${poppins.variable}`}>
      <body className="relative min-h-screen bg-background">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-screen-lg mx-auto">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
